baseurl: /
tileUrl: "//cartodb-basemaps-{s}.global.ssl.fastly.net/light_all/{z}/{x}/{y}.png"
defaults:
  -
    scope:
      path: ""
      type: "cities"
    values:
      layout: "city"
      permalink: "/:slug/"

collections:
  cities:
    output: true
    permalink: /:path/

gems:
  - jekyll-redirect-from
